### ISSUE TITLE
Simple dump functions are not defined (Composer installation)

### ISSUE THREAD

**Issue by nicospor** [php-sage/sage#2]
Hi, I've installed `sage` with Composer in a pre-existing project, the setup is PHP 8.1 with some Symfony components (so `dd` is taken).

I tested it by using the `sage()` and `saged()` functions and it works very well (backtrace dump works too).
However, it seems that their shorthand versions - `s()` and `sd()` respectively - are actually returning simple dumps, while explicitly calling the simple dump functions  - i.e., `ssage()` and `ssaged()` - raises a fatal error because they seem to be undefined.

As far as I understand, the library injects functions in the global namespace, so it shouldn't be necessary to explicitly require the class and/or individual functions with `use` statements, correct?

This is a sample output of calling `saged('testing')`:

![image](https://user-images.githubusercontent.com/53601706/204011005-94e032a7-9f61-4a95-8a4a-e1fa7d134960.png)

while this is the output of `sd('testing')`:

![image](https://user-images.githubusercontent.com/53601706/204011168-aa2546b0-260a-434c-87f7-000cf3ef1eeb.png)

Is this the expected behaviour?

**Comment by raveren** [comment]
First of all, thank you for trying this tiny tool and for reporting the issue! I really appreciate it!

The readme is currently describing changes ahead of the latest release (available through `"php-sage/sage": "dev-main"`), but I am actually already confident enough of the stability.

I went ahead and created a new release, if you'd run `composer update` you should be getting the latest version with shorthands working as advertised :)

Happy coding, let me know if anything annoys you about Sage, I'd appreciate it :))
