### ISSUE TITLE
Is it possible to view complex expanded by default?

### ISSUE THREAD

**Issue by KarelWintersky** [php-sage/sage#3]
Current:

![изображение](https://user-images.githubusercontent.com/2164874/211168193-d3a08e3f-2e5c-4333-a107-1908ca2f2cf8.png)

Expected: 

![изображение](https://user-images.githubusercontent.com/2164874/211168210-6a628993-caa9-4eff-8e84-7b8dce73e59d.png)

**Comment by raveren** [comment]
Sure it is:

```php
!sage(AppRouter::getRoutingRules());

// or 

! s(AppRouter::getRoutingRules());
```

just prepend with `!` :)

**Comment by KarelWintersky** [comment]
Looks like magic. How it works?!?

**Comment by raveren** [comment]
https://stackoverflow.com/a/69890023/179104
