### ISSUE TITLE
drop-in replacement for Kint? s() vs. d()? 

### ISSUE THREAD

**Issue by joemaller** [php-sage/sage#5]
Is there a setting to use the old Kint commands? I'd like to just drop Sage in as a replacement and not have to un-learn a decade of `d()` muscle-memory.

**Comment by raveren** [comment]
`sage` can be typed with one hand, too bad not the brackets too ;)

**Comment by raveren** [comment]
I mean you can always know what you invoke with `sage()`

**Comment by raveren** [comment]
glad to be of help, good luck!
