### ISSUE TITLE
PHP version compatibility

### ISSUE THREAD

**Issue by kitloong1** [php-sage/sage#7]
Hi Rokas,

I'm working on a php v5.3 codebase. I'm downloaded Sage v1.5.4 and required it and I'm getting this error
` Parse error: syntax error, unexpected '=' in phar:///var/www/docroot/lib/sage.phar/Sage.php on line 354`

I checked the file, and I'm suspecting it could be the array destructure that is only available in php v7.1.

Do you know what I can do about it?

**Comment by raveren** [comment]
> I'm working on a php v5.3 codebase

I love that, good luck to you, brave soul :D

PHPStorm loves to zap the old array format into new despite my efforts to prevent it, I tried to find all usages of the new array initializer, I hope I did not miss any, let me know if the latest release works:

https://github.com/php-sage/sage/releases/tag/v1.5.5

**Comment by raveren** [comment]
I'm sorry it took so long for me to notice the issue, hope you get help from sage, I wish I had a 5.3 environment to test it on...

**Comment by raveren** [comment]
Actually found a way to test it and fixed what was still broken, here you go, heartfelt thanks for the issue!

https://github.com/php-sage/sage/releases/tag/v1.5.6
