### ISSUE TITLE
Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-'

### ISSUE THREAD

**Issue by waqast** [php-sage/sage#9]
Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in ./sage/decorators/SageDecoratorsPlain.php on line 226

**Comment by raveren** [comment]
Thanks for the insight! Although the `+` was first to process in

```php
$traceDisplay .= '        ' . $i + 2 . '. ';
```

in all versions since 5.2 I think, but I added the parenthesis, thank you! :)

**Comment by raveren** [comment]
yeah just verified it, the plain-display trace steps are processed correctly since php5.1:
![image](https://github.com/php-sage/sage/assets/364220/f5a548d1-3d98-4fc5-9176-4315e70d947d)
